### ISSUE TITLE
O repo tá vazio

### ISSUE THREAD

**Issue by mentz** [Kanchii/Tibia_Projetin#1]
corrige.

**Comment by Kanchii** [comment]
https://bitbucket.org/weiszin/tibia_projetin/src/master/ '-'

Tava no meu bitbucket por algum motivo XD

Em seg, 18 de mar de 2019 às 16:16, Lucas L. Mentz <notifications@github.com>
escreveu:

**Comment by mentz** [comment]
Obrigado, resolveu :)
